### ISSUE TITLE
Can I create two services  in one linux process

### ISSUE THREAD

**Issue by mengdemao** [COVESA/vsomeip#371]
I want to start two services in the same linux process, is it possible? what to do if it's possible?
Sorry, I am not good at English.

1. create two server in one process.
2. use two configuration file if it's possible

```c
std::shared_ptr<vsomeip::application> app_1 = vsomeip::runtime::get()->create_application("one");
std::shared_ptr<vsomeip::application> app_2 = vsomeip::runtime::get()->create_application("two");

app_1->init();
app_2->init();

app_1->start();
app_2->start();
```

**Comment by feuillatte** [comment]
Due to what start() actually does, which is hijack the thread in which it is called for the vsomeip runtime until that runtime shuts down, you will need to do the respective start() calls in separate threads. 

Define a two void functions that initialize those two services, and then start them via std::thread first_service(service1_function); etc. 

You are now dealing with a multithreaded program however, which comes with additional requirements for exiting cleanly and accessing shared resources (for which std::mutex or atomic variables are handy).
