### ISSUE TITLE
subscribe is not happening

### ISSUE THREAD

**Issue by hari8874** [COVESA/vsomeip#399]
trying to connect two hardware boards client(R-car) using Vsomeip(V3.1.20) and server (Infinium tc399 board)someip standards using CAN protocol
Subscribe is not going to happen but able to see the offer messages from server and find messages from client in wireshark.
![Screenshot from 2022-12-08 18-58-55](https://user-images.githubusercontent.com/89625213/209093866-2a879d9f-4765-4eb4-8fbd-689e390fb99c.png)

**Comment by Zhaoxiaoliang23** [comment]
I also met the same problem. How did you solve it?

**Comment by fcmonteiro** [comment]
Hi,
Are you still having this issue?
Can you provide us your config files for both machines?
Thanks

cc: @goncaloalmeida

**Comment by Zhaoxiaoliang23** [comment]
This problem has been solved, because the VLAN configuration is incorrect. Thanks~


赵晓亮/Xiaoliang Zhao
=========================================================================
经纬恒润 汽车电子事业部 AE诊断工具部
北京市朝阳区酒仙桥路兆维工业园C3座4层，100191 
=========================================================================
Tel: +86 17600805827
Fax: +86 10 64853661
E-mail: ***@***.***

 
From: fcmonteiro
Date: 2023-04-13 17:27
To: COVESA/vsomeip
CC: Moon23; Comment
Subject: Re: [COVESA/vsomeip] subscribe is not happening (Issue #399)
Hi,
Are you still having this issue?
Can you provide us your config files for both machines?
Thanks
cc: @goncaloalmeida

**Comment by hari8874** [comment]
Hi @Zhaoxiaoliang23 can you tell send the VLAN configuration
