### ISSUE TITLE
how open documentation/vsomeip.eap

### ISSUE THREAD

**Issue by GitHubAmos** [COVESA/vsomeip#502]
1. What's content vsomeip.eap?
2. How use it's?

**Comment by reymor** [comment]
vsomeip.eap is Enterprise Architect project. So, in other words, it is the architecture of the library. You shall use Enerprise Architect for openning it. 

The view is something like this:

![image](https://github.com/COVESA/vsomeip/assets/39070043/e8a032a7-f304-416d-a0b1-c9e7248c560a)

![image](https://github.com/COVESA/vsomeip/assets/39070043/fb94560e-978b-4a78-905b-26936fc29d20)

The only thing that I know about this file is that it is outdated. So, it is based on what is called vsomeip2 instead of the current implementation that is called vsomeip3

**Comment by GitHubAmos** [comment]
thanks for your answer
